language: clojure
lein: lein2
jdk:
- openjdk7
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database monsoon_test;' -U postgres
script: lein clj-sql-up run migrate
deploy:
  provider: heroku
  strategy: git
  app: UMDyQTjBfbNTVWLFp629hPQrkOGTv0j3xDUvl+DJW3vSn+6/Ry2JYfPb05HWEbXBLIoI+VrOBif+7IOainVC543uePeQyORJgztORnVJH7rQCFnh8uPhKjKq4EcDY/KjD/6XDLwOv5uv/mTLdMZCKhBohQXzEY/aHoaJ1sI9ZJo=
  api_key:
    secure: eF+lF+TZkrqOyaCWEDhS3vL7/uy09CX4q/ZrMirwyyrk+EGm19n65PvI/xGyKjYd3qW31jZScAIO4hwxJjChCDeChKKPIa5jMB91z0WUu7jNhqDxf7FHtpTj8S4ZwwJsvBNSK23/TzQuyaNABtJEEMBY3mINl+0ub2ZLJWDblUw=
